CREATE DATABASE BD_FIRSTAPP;

USE BD_FIRSTAPP;

CREATE TABLE PRODUTOS
(
	ID INT NOT NULL auto_increment,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QUANTIDADE INT,
    QUANTIDADE_MINIMA INT,
    CONSTRAINT PRIMARY KEY (ID)
);

CREATE TABLE USUARIO
(
	ID CHAR(38) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    LOGIN VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    DATA_HORA_CRIACAO DATETIME NOT NULL,
    DATA_HORA_ULTIMO_ACESSO DATETIME NOT NULL
);